### ISSUE TITLE
Installation fails with Python 3.7

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#113]
It is not possible to install gnpy if you have latest Python version 3.7. I guess because the old versions of some packages listed in requirements.txt are not supported with Python 3.7. Maybe this should be added to the README. Also it may be good to be prepared for when the Anaconda installer comes with Python 3.7 instead of 3.6 which will probably happen soon.

**Comment by ojnas** [comment]
FYI, if I replace all "==" in requirements.txt with ">=" the installation is successful. Running transmission_main_example.py also seems to work normally.

**Comment by dutc** [comment]
Thank you for testing. We haven't trialed any of `gnpy` with Python 3.7 yet. 

There are definitely some features we will make use of (e.g., dataclasses,) and our Onboarding Guide specifies that we are allowed to track Python versions very closely. 

As a matter of practicality, and as you note, we will time our support for Python 3.7 based off of Anaconda's timing. Once they switch over to 3.7 by default, then we will switch over and ensure we support everything. (This ensures that all users and code contributors are able to run the code, because they can run it from a stock Anaconda environment.)

In the meantime, if you'd like to submit a PR with the minimal versioning changes in requirements.txt to get things working, I would happily accept it. Note that we want to be somewhat careful about the versions of the libraries we use to avoid bugs or breaking API changes in our dependent libraries.

**Comment by ojnas** [comment]
Anaconda switched over to python 3.7 some time ago and installing gnpy still fails with 3.7 even though the README just says "gnpy requires Python >3.6.5". To install gnpy with the latest Anaconda I had to create an environment with `conda create -n myenv python=3.6.6`.

**Comment by dutc** [comment]
This should be addressed in v1.0. The requirements.txt was regenerated and package numbers bumped (but fixed.)
