### ISSUE TITLE
Excel file example and source/destination

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#130]
Looking at CORONET_Global_Topology.xls, it might be expected that any node from the "Nodes" sheet could be a source or destination node. But running the following

`python transmission_main_example.py CORONET_Global_Topology.xls Abilene Albany`

results in the confusing output

```
invalid souce node specified, did you mean:                  
[]?                  
'Abilene', replaced with trx Albuquerque
invalid destination node specified, did you mean:                
[]?                
'Albany', replaced with trx Atlanta
```

I assume this is because both Abilene and Albany are degree-2 nodes, which according to Excel_userguide.rst means their type will be set to ILA, and source/destination must be of type ROADM. Maybe it would be less confusing to just set all nodes to ROADM if type is not specified?

**Comment by dutc** [comment]
We can discuss this on our next coder's call. @jeanluc-auge @EstherLerouzic, do you have any comment on this issue?

**Comment by ojnas** [comment]
Hi @EstherLerouzic !

> This was our choice because in usual topologies, ILAs (or Fused) come more often than ROADM and because it leaves the possibility to choose a degree-2 node to be either ILA or Fused which may be interesting to optimize the design.

Yes, but on the other hand, in many topologies most ROADM nodes are only degree-2 (in CORONET Global roughly half the nodes are degree-2). Whatever you choose as default, you will have to set the type explicitly for many nodes.

In general I think defaults should be simple and not try to make "intelligent" guesses since this will just be confusing if you don't know exactly the algorithm behind the guessing. In this specific case, if you don't read Excel_userguide.rst (yeah, I know you should) or look at the code you will be confused about why half the nodes in the xls are not present in the json topology file. Also, I think it would probably be better to return an error message and then stop if the user provides source or destination nodes without transponders instead of running with source and destination nodes in completely different locations.

The choice between ILA and Fused is not automatic if I understand correctly.

Anyway, I'm fine if you want to keep the default as is but then something should be done about the CORONET Global example (e.g. filling the type column explicitly like you say) since that is the first example most users will see.

**Comment by EstherLerouzic** [comment]
Hi @ojnas !
I understand your point ! and you are right I thought the fused choise was automatic at one point but it is not, sorry !
Let's talk of that during our next conf call ! Any of your solution (keeping or changing optional fields, correcting file, and removing the "too smart decision) make sense but I would like to know what is the preference of the group 
thanks a lot for contributing ! I really appreciate your inputs !

**Comment by jeanluc-auge** [comment]
* About source and destination guessing:
This can be misleading and an error code was the original behavior. Then we wanted unexperimented users (unexperimented about the available options) to be able to just run the code without any parameter. Also, the exact syntax of a given node could be painful (sometimes 'trx...' was added with the excel parser for example) so we wanted the code to make an educated guess.
BUT: if you look at the code execution results, it tells what id does, there is no hidden assumption or behavior: at the beginning it says if a source or destination node has been replaced and what choice was made. This way, the unexperimented/1st time user can still see some results, while the experimented user can easily figure what is going on.
What do you think?

*About default ILA and Coronet example:
let me start by saying that the coronet network is a bad example of a typical operator input because ILA locations are not defined, which is always the case (albeit with some flexibility about site skipping, hence the fusing concept in the code) in real operator network topology. It is just a public case that we try to support.
My point is: it is difficult to debate and build argumentation around it since it doesn't reflect reality. I'd rather propose we start the discussion around a real network example.
As for a quick fix:
=> yes definitely we can fill the Coronet type column to ROADM, which will fix the issue. I believe it was initially the case and accidentally removed during code testing. Feel free to propose a PR about it.
Thanks a lot

**Comment by ojnas** [comment]
When working on the fix I just realized another thing: If the user provides the first node in the json as source with correct uid and an incorrect destination like this:

`python transmission_main_example.py CORONET_Global_Topology.json "trx Albuquerque" Whatever`

the program will crash since the destination is replaced with the same node as the source. I will try to provide a fix in my PR.

**Comment by dutc** [comment]
I think same source/destination should be valid in the sense that it should provide some clear output to the user rather than an error message.
