### ISSUE TITLE
power mode and set_roadm_loss

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#148]
I'm very confused by the `set_roadm_loss` in function in `network.py`, which makes the power out from a ROADM independent from input power (in power mode). So if `power_dbm` (in eqpt_config.json for example) is increased, the ROADM loss is also increased which means the OSNR contribution from the ROADM is constant. What is the point of that?

**Comment by dutc** [comment]
@jeanluc-auge Could you look into this and comment?

**Comment by jeanluc-auge** [comment]
Hi Jonas,
it is meant to emulate the power control loop of a ROADM,
some control loops will work on a target power before (sometimes after) the egeress amplifier. This target power is a fixed reference value, thereby independant from the ROADM input power.
The 2nd reason, is that the input power in a roadm is usually a consequence of the architecture limitation (for example power limitation, in the express or drop or add path) therefore you usually set this power and don't change it. And when you do a power sweep to find the optimum klaunched power in spans, you are not trying to optimize the ROADM power. This is why I coded this behavior, but I'd be happy to discuss it further with you.
Thanks for noticing

**Comment by jeanluc-auge** [comment]
I took into account your comment and slighlty modified the way it works, also because there was a small bug when the ROADM ingress power was saturating (the loss calculation did not take it into account).
The behavior I explained is not modified but it should be clearer now. I will submit a PR for the changes.
=> the ROADM loss defined in eqpt_config.json is now the same for gain and power mode. you are right it is confusing otherwise.
=> instead of defining a fixed ROADM output power, a fixed ingress power is defined. For example 0dBm / channel in all ROADM, whatever the span power target or power sweep.
=> TODO next: make this ingress power take into account the signal bandwidth (define a spectrum power density instead of a channel power)

**Comment by jeanluc-auge** [comment]
Following the last ROADM equalization refactor,
the roadm loss concept has been removed and replaced by a Roadm output power target: 
"target_pch_out_db" : -20 that is parametrizable in eqpt config json and is common to all roadms,
it is also parmetrizable in the json file but not yet in the xls (require to add a new column somewhere it would be clear enough: not the eqpt tab). note that this cannot be parametrizable for each direction.
* the power mode and the gain mode will use this same target output power
* the reason is that the roadm loss is something very difficult to calculate or determine and does not reflect the real node configuration
* instead most roadm nodes in commercial product work with a control loop that sets /channel power target
* when reading a commercial design result sheet or extracting information from NMS/controller northbound interface, you typically get this target channel power information rather than roadm loss
* this is in line with our topology model proposal @ IETF

**Comment by jeanluc-auge** [comment]
* The Roadm input power can be customized in the json or xls file with delta_p attribut or gain_target in gain mode. In power mode the delta_p will be sumed to the SI (eqpt_config.json) power_dbm value. If you want the delta_p to be an aboslute span power, you just need to specify power_dbm = 0.
But this can be handy to try different power offset when you upload a design and want to check if it was correctly power optimized...
* in auto_design, the roadm input power is set to power_dbm (delta_p = 0).

**Comment by jeanluc-auge** [comment]
Note that the Roadm input power has now a minimal incidence on the final OSNR since it doesn't change the roadm output power target. The ROADM incremental osnr (egress amplifier osnr contribution) is independent from the roadm input power.
It only changes the gain of the roadm ingress amplfiier, and so its NF and therefore its osnr contribution, but it is a 2nd order effect from NF = f(gain).

**Comment by ojnas** [comment]
Sounds good, I think this issue can be closed. "target_pch_out_db" : -20 looks like a very low default value to me but that is not so important.

**Comment by jktjkt** [comment]
Closing as per [latest comment](https://github.com/Telecominfraproject/oopt-gnpy/issues/148#issuecomment-479404853).
