### ISSUE TITLE
EDFA locations and plotting

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-gnpy#170]
When converting from an xls to a json topology file, ILA type nodes are not included in the json, which means their location information is lost. The locations of all EDFAs are instead set to default (lng=0, lat=0) when later building the network (including EDFAs in ROADM nodes, which logically should have the same location as the ROADM).

One consequence is that the result of plotting from transmission_main_example.py using -pl becomes nonsensical, even if the location of every node is properly specified in the input xls file.

**Comment by dutc** [comment]
I just looked into this more deeply in order to produce some graphics for the upcoming presentation.

There appear to be a couple over overlapping problems. Inserted nodes do not have their locations set correctly, and immutable substructures of nodes are being used in a mutable fashion. We need to dig a bit deeper and fix these two issues, and that should address this bug. 

In general, we should consider whether these nodes are truly immutable or mutable, which requires us to make some larger architectural decisions re: #132

**Comment by EstherLerouzic** [comment]
On the structure, I think that Jean-Luc already proposed some changes in his PR #204.

**Comment by dutc** [comment]
Fixed in v1.2 release.

**Comment by ojnas** [comment]
It looks like this issue is not fully solved in the v1.2 branch. ILA type nodes are still not included when converting from xls to json, which means their location information is lost. Interpolating EDFA locations when later building the network does not necessarily result in the same ILA locations as specified in the xls topology file. Also, the city names of ILA type nodes are lost in the conversion. This means that these city names are not shown when plotting, while e.g. the city names of Fused type nodes are shown.

**Comment by dutc** [comment]
I think this is a separate issue, since it means we need to add enhancements to `convert.py` in order to preserve ILA nodes when converting from XLS to JSON. I'll open a separate issue to track it (#217)
