### ISSUE TITLE
Recommended installation process prevents package update

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#219]
**Describe the bug**
Recommended installation process prevent package update

"python setup.py install"  
creates a "distribution" file (.egg) in the library folder (that avoids the PYTHONPATH declaration). However when updating the program to different working branches (eg latest develop) the gnpy-package is not updated and the newest code is not executed. (eg when using git)

To avoid this behavior I removed all installed packages and installed all packages manually (apt or pip install per package).

**Environment:**
 - OS: linux ubuntu 18.04 on VM
 - Python Version 3.6

**Comment by ojnas** [comment]
Is the package updated if you run "python setup.py install" again after modifying the code (e.g. by checking out a different branch). In that case I would not call it a bug. Also, if you set PYTHONPATH to point at your (modified) code directory, I think that is searched before any "library folder" so you should not have to remove installed packages in order to test modifications.

**Comment by dutc** [comment]
@ojnas is correct. For *development* purposes, it's probably best to use `PYTHONPATH` rather than using `setup.py install`, since you have to rerun the installer every time you make a change.

I think we can leave the README as-is, because it's instructions are targeted for users rather than developers. We can document this in our development/onboarding guide.

**Comment by dutc** [comment]
Given the above explanations, I am going to close this issue. Please feel free to reopen it if you have any questions.

**Comment by ggrammel** [comment]
What is the best way to capture this behavior so that future contributors don't run in the same issue?
