### ISSUE TITLE
Gnpy docker

### ISSUE THREAD

**Issue by jeanluc-auge** [Telecominfraproject/oopt-gnpy#260]
There are several obstacles for newcomers to the project if they are not developpers:
* clone or download the project from github
* have a recent python version 3.6 and soon 3.7: this is sometimes difficult with older os distributions
* have the right environment: requirement.txt and correct python path

The proposed solution is to provide a Dockerfile and a docker-compose.yml to build a gnpy image with the right environnement and run gnpy inside the container. A shared volume (folder) between the host and the container enables the file exchange (topology and configuration json/xls files)

This is typically proposed on other projects, see for example [ATC](https://github.com/apache/trafficcontrol/tree/master/infrastructure/docker) which my new job get me working on ;) as a standalone and easier setup.

I will push next week the dockerfiles needed to build and run a gnpy image with some documentation. However there are 2 possibilities:
*option 1: The dockerfile configuration downloads the source code from GitHub (branch develop for example) directly to the container: this is very easy for newcomers, they don’t have anyhting to deal with Github, except copy past the dockerfiles.
*option 2: The dockerfile configuration copies the source code from the local drive into the container: this means that the user already cloned the Git repo. But it gives more control for developers because they can modify the code locally before building the container to test the code. This 2nd option is used in ATC.

Could you comment and tell me what you prefer? 
And do you think it can provide value ?

**Comment by jktjkt** [comment]
I think that it makes a lot of sense to provide a prepackaged tool for newcomers to use. Docker looks like a great match for this because it has a big momentum of users, and the majority of users like it that way.

The situation is a bit different with developers. I think that Python has great built-in tools for managing virtual environments, and setting one up is a matter of running one simple command. I do not see much added value with Docker here (well, unless people are stuck on something like RHEL6 for their work machine). Someone who works with GNPy should understand Python reasonably, and I think that `venv` is a part of that understanding. If a fellow developer wants to run Docker to make their life easier, be my guest of course -- but to me, it does not look like a great use of resources to create a container first, and then set up a venv inside. That's one layer too many for my personal taste.

This means that, from my point of view, this is how a perfect solution should look like:

- It's a one-click thing for users. No need to set up anything.
- We have it under our control. This means CI coverage and no manual steps.

I think you know that, but Esther said that someone from Orange (but not you) will come talk about how they already packaged PSE with Docker. Just making sure that there's no duplicate effort here, but you are probably aware of that activity.

**Comment by ojnas** [comment]
> The proposed solution is to provide a Dockerfile and a docker-compose.yml to build a gnpy image with the right environnement and run gnpy inside the container.

I'm not a Docker expert so this may be a stupid question but why docker-compose and not just a Dockerfile? I thought compose was for defining multi-container applications.

I think providing a Docker solution is a good idea but I wonder how many non-developers actually run Docker on their computers. I'm not sure it's less of an obstacle but I may be wrong.

**Comment by jeanluc-auge** [comment]
Thanks for your interest,
Ahmed is the other person from Orange. His package is about TPCE and postman interaction with Flask.
On my side I focused on solving our deployment issues and tried to find a way that allows:
* to copy the code from Github (and not only from the host)
* have a shared folder with the host to exchange topology files for example
* avoid to use specific docker options when starting the container, to ease the user experience
This is why I came up with docker-compose:
* here, the docker-compose.yml file is for the parametrization of the container. The same could be achieved with options in docker run but the yml file replace them so that the user doesn't have to know the syntax of these options or write them every time (can be quite long and cumbersome).
* if the user wants to change the yml configuration (for example the shared folder path on the host or the entrypoint: bash vs executing transmission_main) it's easy and more importantly the image does not need to be rebuilt. So it is very quick.
* For example it is not possible to bind mount the shared_folder volume with a specific path on the host with only a Dockerfile. Any host specific path can only be a docker run -v option (or a yml config) because the Dockerfile is meant to be generic and not tied to a specific host.
    => without a docker-compose.yml you would have to specify as an option the shared volume name and its path on the host and the container, everytime you run the container.

That's my understanding and the results of my attempts, but like you Jonas I'm not a yml expert.

Eventually we can merge Ahmed and I contributions after you see the proposals.

**Comment by jeanluc-auge** [comment]
Hi Jonas, did you remove your comment? I was glad you tested it on windows and it worked: thanks.
Also I implemented your good suggestion of copying the content of /examples into the /shared_folder.
Let me know if you want me to update the PR.

**Comment by ojnas** [comment]
I think you are referring to my comment on the PR [here](https://github.com/Telecominfraproject/oopt-gnpy/pull/265#issuecomment-504074713). Actually, I also tried copying the examples folder and it can be done in the Dockerfile, see my comment [here](https://github.com/Telecominfraproject/oopt-gnpy/pull/265#issuecomment-504221616), but I don't have a strong preference for how it's implemented.

**Comment by jktjkt** [comment]
We're now building these images automatically. They are available via https://hub.docker.com/r/telecominfraproject/oopt-gnpy .
