### ISSUE TITLE
docs: do we need and want Anaconda?

### ISSUE THREAD

**Issue by jktjkt** [Telecominfraproject/oopt-gnpy#287]
(This is related to #284.)

Our installation instructions currently suggest people to use Anaconda, and have been doing so since commit b505a1ae. Can someone comment on why this is recommended over Python's native `venv` module?

For a reference, here's how I've been working with Python environments:

```console
jkt@kopac ~/TIP $ python3.6 -m venv py-3.6
jkt@kopac ~/TIP $ source py-3.6/bin/activate
(py-3.6) jkt@kopac ~/TIP $ cd oopt-gnpy/
(py-3.6) jkt@kopac ~/TIP/oopt-gnpy[develop] $ pip install --editable .
```

I find this a bit easier than dealing with an external tool, Anaconda, that I've never used before. Perhaps it makes the experience much better on, say, Mac or Windows?

The main reason why I'm asking here is becaue [anaconda discourages running `pip`](https://www.anaconda.com/using-pip-in-a-conda-environment/), and I would like to use `pip`'s `--editable` option for easy installations...

**Comment by ggrammel** [comment]
AFAIR it was suggested by James to address some issues we had before such as #55, #98, #99, #103, #105, #111

Form my perspective the Anaconda distribution creates a comfortable user environment to play with python and gnpy. I am using Anaconda/spyder since that time and it worked for me so far OK.
The only recurring issue which predates the use of Anaconda is that I have always the suspicion to use the wrong import files while testing and have no way to verify the truth.  Meticulously following a Readme certainly helps but does not abate the doubts and Anaconda doesn’t help me there either.
