### ISSUE TITLE
NF of a variable gain EDFA

### ISSUE THREAD

**Issue by Tobelightbeam** [Telecominfraproject/oopt-gnpy#364]
In gnpy.core.elements, there is a method _nf in class EDFA, which is used to calculate the nf according to the type_variaty given the gain_target. The following is part of the source code.

def _nf(self, type_def, nf_model, nf_fit_coeff, gain_min, gain_flatmax, gain_target):
        pad = max(gain_min - gain_target, 0)
        gain_target += pad
        dg = max(gain_flatmax - gain_target, 0)
        if type_def == 'variable_gain':
            g1a = gain_target - nf_model.delta_p - dg
            nf_avg = lin2db(db2lin(nf_model.nf1) + db2lin(nf_model.nf2) / db2lin(g1a))

As seen in the code, the method assumps that a 'variable gain' EDFA is implemented through 2 mid_stage. However, the gain for the first stage, which i think is "g1a", seems confused.

For simplicity, let's assum that gain_target is not greater than gain_flatmax, then dg equals to (gain_flatmax - gain_target). Substituting this relationship into the expression for g1a, we can get: 
'g1a = 2*gain_target - nf_model.deltap - gain_flatmax'

The aboving equation makes me confused:
1. Why is g1a calculated like that?
2. What is the meanning of nf_model.deltap?

I'd be gratful if anyone can help.

**Comment by ojnas** [comment]
Hi @Tobelightbeam,

for more information about the variable_gain NF model you can have a look at the estimate_nf_model method in gnpy.core.science_utils. The model tries to estimate how NF depends on gain given minimum and maximum NFs as input.

That said, I have studied this code myself without being able to understand the exact reasoning behind it. The person who implemented it is not involved in the project anymore. If you are able to make sense of it, please tell.

**Comment by Tobelightbeam** [comment]
Hi Jonas,

Thanks for your advice. I have looked at the estimate_nf_model method and got some points.

There is a key equation (derived from the 2-stage vabiable-gain-EDFA model) behind the method:
nf = nf1+nf2/g1a,
where nf is the total noise figure, nf1 is noise figure of the 1st-coil, nf2 is noise figure of the 2nd-coil. 

The two coils is connected by an varible optical attenuator(VOA) to form the 2-stage model and g1a = g1 - a where g1 is the gain of the 1st-coil and a is the attenuation. The overall gain is adjustied by tunning the VOA while g1 and g2 stay unchanged.

Therefore,
nf_min = nf1 + nf2/g1a_max
nf_min = nf1 + nf2/g1a_min
The aboving equations could answer the quetion how are nf1 and nf2 calculated from nf_min, nf_max, g1a_min and g1a_max.

Since nf_min and nf_max are already in parameters of variable-gain model, calculating g1a_min and g1a_max is key.

According to the s-stage model:
gain_max = g1a_max + g2,
gain_min = g1a_min +g2.
But g2 is unknown, gain_max and gain_min can't be obtained. 

To address this issue, the estimate_nf_model raised a key assumption "delta_p =5". The reason for this assumption is not clear. I don't know why this value is set to 5.

Besides,  the logic behind the calculation is not consistent.
To be detailed, from the formula "g1a_max = gain_max - delta_p", we may conclude that "delta_p is just g2". However, this conclusion collides with the formula "g1a_min = gain_min - (gain_max-gain_min) - delta_p".
So, the meanning of "delta_p" is still a secret for me :( 

That's all I could get from the code so far..

**Comment by jeanluc-auge** [comment]
Hi all, 
Esther pointed to me there was a question regarding a contribution I made some time ago, so let me try to clarify if possible. In any case, it certainly means that additional documentation and/or code commenting is needed. These were my early days into coding, and now I would never rewrite the same code without a very detailed docstring, which is clearly missing.

Regarding the model itself, it tries to figure what is the amplifier NF profile when a more precise polynomial description is not available. Therefore it is an approximation, and there is some empirism, like the delta_p parameter. It is also the result of my experience at modelling amplifiers when I used to specify them when working for an equipment supplier.

Basically this modelling aims at guessing the NF profile based on its sole NFmin, NFmax, gain_min and gain_max information when no better information is available. I considered 3 possibilities before retaining the actual code:

1- make a basic interpolation: I found this very inferior and far from real amplifier profiles so I did not retain this method.

2- model a 2 stages amp model and parametrize every needed parameters such as 1st stage gain, 2nd stage gain, power differences between 1st & 2nd stage etc... I did not retain this method because some of these parameters are not constant, and parametrizing everything would defy the original intent that was providing a model with very little information. If you don't know the polynomail NF vs gain of an amplifier, it's likely you don't know about its internal power and gain allocation between 1st and 2nd stage either.

3- The method I eventually retained was to model a 2 stages amp and make generic assumptions about missing parameters (like delta_p  = 5) and checking it had minimum impact.

# About the model itself, there are 2 parts:
- the 1st part in gnpy.core.science_utils/estimate_nf_model() determines the model parameters from the inputs nf_min and nf_max, gain_min and gain_max. The goal is to calculate the NF of the 1st and 2nd stages (before and after the voa) nf1 & nf2. It is assumed that those are Cte regardless of g1 and g2 (1st and 2nd stage gains), which is an approxmation as there is usually a dependency ~1dB (or more at extreme mini gain values).
- The 2nd part in elements/Edfa calculates the overall nf based on previously determined nf1 & nf2: nf = nf1+nf2/g1a.
Now switching to dBs:
- g1, g2: 1st stge and 2nd stage gains
- g1a = g1-voa: g1a is the gain after the internal voa, while g1 is the gain before the voa
- voa = gain_max - gain: to control amplifier flatness
About your questionning on the meaning of delta_p:
- delta_p = p2 - p1: where p1,2 are the 1st and 2nd stage output powers
- g1a_max = gain_max - voa_min - delta_p = gain_max - delta_p
- g1a_min = gain_min - voa_max - delta_p = gain_min - (gain_max-gain_min) - delta_p
since voa_min = 0 at maximum gain and voa_max = gain_max-gain_min at minimum gain.

# Discussion:
- Provisionning a residual min voa attenuation so that VOA_min>0 is more physically accurate but I found it did not change the model numerical behaviour, so I dropped it and chose voa_min=0.

- Cte nf1 & nf2 vs arbitrary polynomial model nf1=f(g1), nf2=f(g2) with ~1dB range. This provides some improvement but it is rather complex and arbitrary.

- is delta_p a constant across the gain range and why chosing 5dB? This is open to debate, but it reflects that by design (...) amplifiers 1st stage cannot reach the same high power level as the 2nd stage. Cte delta_p brings simplification and is correct if amplifiers are used with output voa that maintain p2=Cte=pmax (for gain<gain_max). If not, a more realistic model is p2_max - p1_max = delta_p instead of p2 - p1 = delta_p. But nf becomes dependant on the output power at which the amplifier operates (which is a phisical reality), and it becomes complex to derive generic nf1, nf2 from absolute nf_min and nf_max values.

**Comment by Tobelightbeam** [comment]
Hi, @jeanluc-auge and all.
Thanks for the detailed docstring. It really helped me understading the model of a variable gain EDFA.
