### ISSUE TITLE
GNPy adoptes dijkstra algorithm

### ISSUE THREAD

**Issue by indayara** [Telecominfraproject/oopt-gnpy#437]
**Is your feature request related to a problem? Please describe.**

I see that the GNPy adopted the Yang path model for the path computation process. 
Is it possible to integrate/apply different algorithms for the path computation process?

Thanks in advance.
Best regards,

**Comment by jktjkt** [comment]
Hi, right now this is not possible (but it should be possible to compute the path externally and send back a request which -- effectively -- has the path already set in stone). What is your use case for this feature?

(I'm also moving this to a GitHub discussion because it's not really a bugreport.)
