### ISSUE TITLE
Excel questions and observations

### ISSUE THREAD

**Issue by owens-bill** [Telecominfraproject/oopt-gnpy#58]
This is the list of questions and observations I've come up with while putting the NYSERNet network into the Excel input format:

Nodes:
* I don't know what "Region" means.

Links page:
* For each of my spans, I know the end-to-end loss, but not the loss per km. It's obviously trivial to calculate one from the other, but I think it would be easiest to enter the information as end-to-end loss.
* I am not sure what's being asked for in the PMD column: characteristic PMD measurement for the fiber (which should come from the fiber data) or measured/calculated PMD for the link. I don't have the ability to measure PMD so I can't report that in any case.
* I'm not sure what "SRG interest" refers to.

**Comment by dutc** [comment]
I can help answer some of these.

"Region" is likely a holdover from the CORONET topology. CORONET separates its network into geographical regions (Europe, Asia, Continental US.) This information is not used by `gnpy`, and I think this field can be omitted.

**Comment by ggrammel** [comment]
I also wanted to give it a try but didn't start yet. However before starting I asked Esther for the steps to take so that it is easier for me to play with it. Attached what I got (all Kudos to Esther!)

How to prepare the input Excel file
-----------------------------------

transmission_main_example.py gives the possibility to use an input Excel file instead of a json file. The program then will generate the corresponding json file for you.

The file named 'meshTopologyExampleV2.xls' is an example.

In order to work the excel file MUST contain at least 2 sheets
- Nodes
- Links

(In progress) The File MAY contain an additional sheet:
- Eqt

Nodes sheet
-----------

Nodes sheet contains seven columns
each line represents a "node" (ROADM site or an in line amplifier site, ILA)

- "City" is mandatory.
It is used as the name of a node of the digraph. It accepts letters, numbers, comma, underscore, dash, blank... (not exhaustive).
**It MUST be unique** 

- "Type" is not mandatory. 
   - If not filled, it will be interpreted as an 'ILA' site if node degree is 2 and as a ROADM otherwise.
   - If filled, it can take "ROADM" or "ILA" values. If another string is used, it will be considered as not filled.

- "State", "Country", "Region" are not mandatory.  

- "Longitude", "Latitude" are not mandatory. 
They should contain numbers.

**There MUST NOT be empty line(s) between two nodes lines**


Links sheet
-----------

Links sheet must contain sixteen columns.
Links sheets MUST contain all links between nodes defined in Nodes sheet.
Each line represents a 'bidir link' between two nodes. The two direction are represented on a single line with "east cable from a to z" fields and "west from z to a" fields. Values for 'a to z' may be different from values from 'z to a'. 
'z to a' direction MUST NOT be repeated in a different line.
(current parser does not support multiple fiber pairs)

Parameters for "east cable from a to z" and "west from z to a" are detailed in 2x7 columns. If not filled, "west from z to a" is copied from "east cable from a to z".

For example, a line filled with 

node6 ; node3 ; 80 ; SSMF ; 0.2 ; 0.5 ; 0.5 ; 0.1 ; cableB ;  ;  ; 0.21 ; 0.2 ;  ;  ;  

will generate a unidir fiber span from node6 to node3 with [node6 node3 80 SSMF 0.2 0.5 0.5 0.1 cableB] attributes and a fiber span from node3 to node6 [node6 node3 80 SSMF 0.21 0.2 0.5 0.1 cableB] attributes. 

- "NodeA" and "NodeZ" are Mandatory. 
They are the two endpoints of the link. They MUST contain a node name from the "City" names listed in Nodes sheet.

- "Distance km" is not mandatory. 
It is the link length.
If filled it MUST contain numbers. If empty it is replaced by a default "80" km value. 
If value is below 133 km, it is considered as a single (bidirectional) fiber span.
If value is over 133 km the transmission_main_example.py program will automatically suppose that intermediate span description are required and will generate fiber spans elements with_1,_2, ... trailing strings which are not visible in the json output.

- "Fiber type" is not mandatory. 
If filled it must contain types listed in eqpt_config.json in "Fiber" list "type_variety".
If not filled it takes "SSMF" as default value.

- "Lineic att" is not mandatory. 
It is the lineic attenuation expressed in dB/km.
If filled it must contain positive numbers.
If not filled it takes "0.2" dB/km value

- "Con_in", "Con_out" are not mandatory and are not used yet. 
They are the connector loss in dB at ingress and egress of the fiber spans.
If filled they must contain positive numbers.
If not filled they take "0.5" dB default value.

- "PMD" is not mandatory and and is not used yet. 
It is the PMD value of the link in ps.
If filled they must contain positive numbers.
If not filled, it takes "0.1" ps value.

- "Cable Id" is not mandatory. 
If filled they must contain strings with the same constraint as "City" names.



(in progress) Eqpt sheet 
              ----------
# to be completed #
Eqt sheet is optional. It lists the amplifiers types and characteristics on each degree.
If the sheet is present, it MUST have as many lines as egress direction defined in Links Sheet.

**Comment by jeanluc-auge** [comment]
It is true that total loss input would be more convenient, but it brings ambiguity if you add the length because the lineic loss (dB/km) becomes the adjustable. It should not:
-lineic loss is important for nonlinear calculation
-high span loss may often be due to additional connector and odf losses but not lineic loss, which could somehow render the simulation too optimistic in term of non linear effect.
=> my take here is to complement span loss with connector loss and keep lineic loss between 0.2-0.22dB/km.
This could be further discussed during the Thursday call.
SRG is for sharing risk group : in future restoration scenario we may want the code to look at the cable id so that traffic is not rerouted over the same broken cable. And also to calculate disjoint paths.

**Comment by owens-bill** [comment]
I see the justification for keeping lineic and end connector loss separate, since that will also affect Raman calculations, but there's also the contribution of splices in the running line fiber. I suppose if those are small enough they'll just be averaged into the lineic loss number, and if they're large (or if there is a glass-through) that should be treated as two fused segments with the extra loss expressed as end connector losses on each segment.

**Comment by jeanluc-auge** [comment]
yes, I would see it that way as well.
Note that with the new Fused span feature you get this glass through loss specified. For now it is [hardcoded](https://github.com/Telecominfraproject/gnpy/blob/develop/gnpy/core/elements.py#L110) as 1dB but should be read from json or xls in future code fixes.
