### ISSUE TITLE
EDFA parameters and booster-less type

### ISSUE THREAD

**Issue by berahtlv** [Telecominfraproject/oopt-gnpy#62]
It will be convenient to enter EDFA parameters closer to the defined by the equipment configuration. Our equipment vendor uses two types of config for different system types:
1. Without OSC channel
  1.1 Gain (already implemented)

2. With OSC channel
  2.1 Filter structure output power (target channel power before amplification - at amp input, and is frequency dependent)
  2.2 Booster and Preamplifier Po/ch (target channel power after amplification - at amp output)
  2.3 Booster-less amplifier (OSC channel termination)

In second case Booster Gain can be calculated from entered parameters (2.2 and 2.1) and Preamp Gain from line input power against target power (2.2). Both parameters are dependent from particular ROADM direction goals, so each direction and one directions Booster/Preamp can use its own.

For short spans 2.3 amplifier type can be used, in that case amplifier is just attenuation source.

Edit:
2.1 definition

**Comment by jeanluc-auge** [comment]
In current code, the power / channel Po/ch (Pch) results from the channel power defines in the Tx and the amplifiers gain.
* Tx (transponder laser before ROADM add&drop) is defined in a so called spectral information tupple: [ref tupple](https://github.com/Telecominfraproject/gnpy/blob/master/examples/transmission_main_example.py#L86).
* Amplifier gain can be user input but if not, the code will automatically set it (if no amplifiers or no operational gain for the amplifiers is specified in the json or xls topology files. The code automatic gain setting will just compensate the preceding element loss
=> As a result the same Pch is launched in all fiebrs and equal to the Tx power tupple.
Also be careful that the power is defined / wavelength so beware to adjust it if you change the baud rate.
So, you may conver your eqpt use case by adjusting the gain for each ROADM and related directions so that you get the required Pch so the tool is compliant. Now, making it more user friendly would require an xls parser that takes Pch rather than gain as input. Would that adress your need?

**Comment by berahtlv** [comment]
You mean if baud rate is lower, then Pch should be lowered?

Gain entered in 'Eqpt' sheet is used for Egress amplifier only (a to z) or Ingress amplifier only (z to a) and second link amplifiers gain is automatically calculated (Egress or Ingress). I think it should be possible to choose manually Ingress and Egress amplifier types.

**Comment by jeanluc-auge** [comment]
sorry for the late reply,
* Yes, pch defined in the [ref tupple](https://github.com/Telecominfraproject/gnpy/blob/master/examples/transmission_main_example.py#L86) should be modified according to the baud rate (lower for lower baud rate).
* The Eqpt sheet is supposed to behave like you said: possibility to chose manually different ingress and egress amplifier types with different gains. If not, please let us know. this way you can have different power settings for each RAODM direction.
