### ISSUE TITLE
Coronet example throws errors

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/oopt-gnpy#94]
- Coronet did not work:
ggrammel-mbp:examples ggrammel$ python3 transmission_main_example.py coronet_conus_example.json
coronet_conus_example.json
Traceback (most recent call last):
  File "transmission_main_example.py", line 102, in <module>
    network = load_network(args.filename, equipment)
  File "/projects/github/test/oopt-gnpy-develop/gnpy/core/network.py", line 32, in load_network
    return network_from_json(json_data, equipment)
  File "/projects/github/test/oopt-gnpy-develop/gnpy/core/network.py", line 46, in network_from_json
    el = cls(**el_config)
  File "/projects/github/test/oopt-gnpy-develop/gnpy/core/elements.py", line 168, in __init__
    super().__init__(*args, params=FiberParams(**params), **kwargs)
TypeError: __new__() missing 1 required positional argument: 'type_variety'

**Comment by jeanluc-auge** [comment]
Hi Gert,
thanks for the report: fortunately it's not a bug but the json file that is outdated. Since then we have added a type_variety description for Fiber (like SSMF) so that it's optical characteristics do not need to be repeated N times in the topology json. Instead the type variety characterisitics are described in the eqpt_config json file. 
Moving forward on this:
* you can check there is no bug by running the up to date version CORONET_Global_Topology.json/xls
* we need to clean up the repository from such outdated files: I'll start in my current pull request
* we could also amend the code to provide a default SSMF value when the type_variety is missing

**Comment by ggrammel** [comment]
Jean-Luc,

I was using the develop branch for my testing and ran into the issue. My suspicion was also that something in CORONET might be fishy, since the other test worked without issues. Nevertheless we should aim to fix the issue before pushing into master. If that simply means to update the file – the better it is.
Agree with you that cleaning up a bit the repository from outdated files. It’s getting confusing and better to clean up now.

Thanks

Gert

**Comment by ggrammel** [comment]
check before master is released
